# https://materialdesignicons.com/
# https://concourse-ci.org/resources.html
# fly -t kairohm set-pipeline --pipeline netbox --config .\concourse-ci.yml
resources:
  # https://github.com/concourse/git-resource
  - name: git-repo
    type: git
    icon: git
    public: true
    # check_every: 24h
    source:
      uri: https://github.com/Zeigren/netbox_docker.git
      branch: main

  # https://github.com/concourse/registry-image-resource
  - name: github-image
    type: registry-image
    icon: github
    public: true
    check_every: never
    source:
      repository: ghcr.io/zeigren/netbox_docker
      username: Zeigren
      password: ((github_token.token))

  - name: dockerhub-image
    type: registry-image
    icon: docker
    public: true
    check_every: never
    source:
      repository: zeigren/netbox
      username: zeigren
      password: ((dockerhub_password.password))

# https://concourse-ci.org/jobs.html
jobs:
  - name: build-and-push
    public: true
    plan:
      - get: git-repo
        trigger: true
      - load_var: version-tag
        file: git-repo/version
      - load_var: commit-date
        file: git-repo/.git/commit_timestamp
      # https://concourse-ci.org/tasks.html
      - task: build-docker-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
              # https://github.com/concourse/oci-build-task
          inputs:
            - name: git-repo
              path: .
          outputs:
            - name: image
          params:
            BUILD_ARG_VERSION: ((.:version-tag))
            BUILD_ARG_DATE: ((.:commit-date))
          run:
            path: build
      - task: build-docker-image-nextbox
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: git-repo
              path: .
          outputs:
            - name: nextboximage
          params:
            BUILD_ARG_VERSION: ((.:version-tag))
            BUILD_ARG_DATE: ((.:commit-date))
            BUILD_ARG_NEXTBOX: True
          run:
            path: build
      - in_parallel:
          - put: github-image
            params:
              image: image/image.tar
              additional_tags: git-repo/tags_version
          - put: dockerhub-image
            params:
              image: image/image.tar
              additional_tags: git-repo/tags_version
          - put: github-image
            params:
              image: nextboximage/image.tar
              additional_tags: git-repo/tags_nextbox
          - put: dockerhub-image
            params:
              image: nextboximage/image.tar
              additional_tags: git-repo/tags_nextbox
