version: "3.8" # https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  caddy:
    image: caddy:latest
    # https://hub.docker.com/_/caddy
    volumes:
      - static:/var/www/netbox/static
      - media:/var/www/netbox/media
      - caddy_data:/data
    networks:
      - caddy
    ports:
      - "80:80"
      - "443:443"
    configs:
      - source: netbox_caddyfile
        target: /etc/caddy/Caddyfile
    environment:
      # https://caddyserver.com/docs/automatic-https#overview
      - DOMAIN=netbox.yourdomain.test

  netbox:
    image: zeigren/netbox:latest # ghcr.io/zeigren/netbox_docker:latest
    # https://hub.docker.com/r/zeigren/netbox
    # https://github.com/netbox-community/netbox
    # https://netbox.readthedocs.io/en/stable/
    volumes: # https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
      - static:/usr/src/app/netbox/static
      - media:/usr/src/media
    secrets: # https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets
      - netbox_db_password
    networks: # https://docs.docker.com/compose/compose-file/compose-file-v3/#networks
      - caddy
      - netbox
    environment: # https://docs.docker.com/compose/compose-file/compose-file-v3/#environment
      - DATABASE_PASSWORD=DOCKER-SECRET->netbox_db_password
      - ALLOWED_HOSTS=netbox.yourdomain.test
      # CREATE SUPERUSER ONCE THEN DELETE THESE
      # - CREATE_SUPERUSER=True
      # - DJANGO_SUPERUSER_USERNAME=admin
      # - DJANGO_SUPERUSER_EMAIL=admin@admin.com
      # - DJANGO_SUPERUSER_PASSWORD=admin

  postgres:
    image: postgres:alpine
    # https://hub.docker.com/_/postgres
    volumes:
      - netbox_db:/var/lib/postgresql/data
    secrets:
      - netbox_db_password
    networks:
      - netbox
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/netbox_db_password
      - POSTGRES_USER=netbox
      - POSTGRES_DB=netbox

  redis:
    image: redis:alpine
    # https://hub.docker.com/_/redis
    networks:
      - netbox

volumes: # https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference
  static:
  media:
  caddy_data:
  netbox_db:

configs: # https://docs.docker.com/compose/compose-file/compose-file-v3/#configs-configuration-reference
  netbox_caddyfile:
    external: true

secrets: # https://docs.docker.com/compose/compose-file/compose-file-v3/#secrets-configuration-reference
  netbox_db_password:
    external: true

networks: # https://docs.docker.com/compose/compose-file/compose-file-v3/#network-configuration-reference
  caddy:
  netbox:
