version: "3.7"
# https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  nginx:
    image: nginx:alpine
    # https://hub.docker.com/_/nginx
    networks:
      - nginx
    volumes:
      - static:/var/www/netbox/static
      - media:/var/www/netbox/media
      - ./config/netbox_nginx.conf:/etc/nginx/templates/nginx.conf.template
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - ./config/yourdomain.test.crt:/etc/nginx/certs/yourdomain.test.crt
      # - ./config/yourdomain.test.key:/etc/nginx/certs/yourdomain.test.key
    ports:
      # CHANGE TO "80:80" IF USING NGINX FOR SSL TERMINATION
      - "9080:80"
      # UNCOMMENT IF USING NGINX FOR SSL TERMINATION
      # - "443:443"
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx
      # https://nginx.org/en/docs/ngx_core_module.html#worker_processes
      - NGINX_WORKER_PROCESSES=auto
      # https://nginx.org/en/docs/ngx_core_module.html#worker_rlimit_nofile
      - NGINX_WORKER_RLIMIT_NOFILE=65535
      # https://nginx.org/en/docs/ngx_core_module.html#worker_connections
      - NGINX_WORKER_CONNECTIONS=65535
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size
      - NGINX_CLIENT_MAX_BODY_SIZE=10m
      # https://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_timeout
      - NGINX_CLIENT_BODY_TIMEOUT=30s
      - NGINX_HOST=localhost
      # UNCOMMENT IF USING NGINX FOR SSL
      # - NGINX_SSL_CERT=yourdomain.test.crt
      # - NGINX_SSL_KEY=yourdomain.test.key

  netbox:
    image: zeigren/netbox:latest # ghcr.io/zeigren/netbox_docker:latest
    # https://hub.docker.com/r/zeigren/netbox
    # https://github.com/netbox-community/netbox
    # https://netbox.readthedocs.io/en/stable/
    volumes: # https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes
      - static:/usr/src/app/netbox/static
      - media:/usr/src/media
    networks: # https://docs.docker.com/compose/compose-file/compose-file-v3/#networks
      - nginx
      - netbox
    environment: # https://docs.docker.com/compose/compose-file/compose-file-v3/#environment
      - DATABASE_PASSWORD=CHANGEME
      - ALLOWED_HOSTS=netbox.yourdomain.test
      # CREATE SUPERUSER ONCE THEN DELETE THESE
      # - CREATE_SUPERUSER=True
      # - DJANGO_SUPERUSER_USERNAME=admin
      # - DJANGO_SUPERUSER_EMAIL=admin@admin.com
      # - DJANGO_SUPERUSER_PASSWORD=admin
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:alpine
    # https://hub.docker.com/_/postgres
    volumes:
      - netbox_db:/var/lib/postgresql/data
    secrets:
      - netbox_db_password
    networks:
      - netbox
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/netbox_db_password
      - POSTGRES_USER=netbox
      - POSTGRES_DB=netbox

  redis:
    image: redis:alpine
    # https://hub.docker.com/_/redis
    networks:
      - netbox

volumes: # https://docs.docker.com/compose/compose-file/compose-file-v3/#volume-configuration-reference
  static:
  media:
  netbox_db:

networks: # https://docs.docker.com/compose/compose-file/compose-file-v3/#network-configuration-reference
  nginx:
  netbox:
